
server:
  port: 8082 
spring:
  application:
    name: "config-service"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JarlNuramon/microserviceproperties.git
          username: 
          password: 
          clone-on-start: true
